"""Content for the practice area pages.

Edit the wording here, then run:  python3 scripts/build-practice-pages.py

Markup: **bold** becomes <strong>. Plain "&" and quotes are escaped for you.
Each page has: intro, areas (accordions), steps, faqs, checklist, related.
An area is (id, title, intro, [(heading, [bullets])], closing_paragraph).
"""

PAGES = {}

# ---------------------------------------------------------------- Family law
PAGES['family-law.html'] = dict(
    nav_title='Family Law',
    title='Family Law | Divorce, Children, Maintenance & Protection Orders | Linda Chirwa Attorneys',
    meta='Divorce, child care and contact, maintenance and protection orders in South Africa. Honest advice, settlement first, litigation when needed. Linda Chirwa Attorneys.',
    h1='Family Law',
    lead='Divorce, children, maintenance and protection orders, handled with discretion and a clear plan from the first consultation.',
    intro='Family disputes are emotional, and they are often urgent. Decisions made in the first weeks, about where the children live, who stays in the home and what is agreed in writing, tend to shape the outcome for years. **We give you a clear picture of your options and the likely costs before you commit, and we aim to settle a matter where that protects you and your children.** Where a matter has to be fought, we appear in the Magistrates\' Courts, the Regional Courts and the High Court.',
    areas=[
        ('divorce', 'Divorce & Separation',
         'A court grants a divorce once it is satisfied that the marriage has broken down irretrievably. Most divorces can be settled by agreement, which is faster and cheaper than a trial.',
         [('What we handle', [
             'Uncontested divorces and settlement agreements',
             'Contested divorces, including division of the joint estate and accrual claims',
             'Spousal maintenance and claims for forfeiture of patrimonial benefits',
             'Rule 43 applications for interim maintenance, contact and a contribution to legal costs',
             'Tracing, valuing and protecting assets, including pensions and business interests',
             'Setting aside or varying existing orders where circumstances have changed']),
          ('Your marital regime', [
             'Whether you married in or out of community of property, and with or without accrual, decides how assets are divided',
             'If you signed an antenuptial contract, we start by reading it',
             'Our notaries can also advise on antenuptial contracts through our <a href="notarial-services.html#anc">Notarial Services</a>'])],
         'Fault is not required to obtain a divorce, but conduct can matter for forfeiture and for maintenance. We advise early on what a court is likely to do.'),
        ('children', 'Children: Care, Contact & Guardianship',
         'The Children\'s Act 38 of 2005 puts the best interests of the child first. Parents hold parental responsibilities and rights, and the law does not favour mothers over fathers or the reverse.',
         [('What we handle', [
             'Parenting plans and agreements on where children live and when they see each parent',
             'Applications for care, contact and guardianship',
             'Relocation disputes, including moves between provinces or abroad',
             'Consent to travel and passport disputes',
             'Parental rights of unmarried fathers',
             'Children\'s Court matters and reports from the Office of the Family Advocate'])],
         'Courts decide on the facts: who has cared for the child, the child\'s needs and each parent\'s ability to meet them. A well-drafted parenting plan often avoids a court fight altogether.'),
        ('maintenance', 'Maintenance',
         'Both parents have a duty to support their children, according to their means. Maintenance is dealt with in the Maintenance Court, in a divorce, or by agreement made an order of court.',
         [('What we handle', [
             'Applications to fix, increase or reduce maintenance',
             'Enforcing orders, including attachment of salary and prosecution for default',
             'Recovering arrears',
             'Maintenance for children who cannot yet support themselves, for example while studying',
             'Spousal maintenance in or after a divorce',
             'Responding to maintenance claims against you'])],
         'A maintenance order can be changed if circumstances change materially, for example loss of income or a change in the child\'s needs.'),
        ('protection', 'Protection Orders & Domestic Violence',
         'The Domestic Violence Act 116 of 1998 protects people in domestic relationships from physical, sexual, emotional, verbal, psychological and economic abuse, as well as intimidation, harassment and stalking.',
         [('What we handle', [
             'Applications for interim and final protection orders at the Magistrate\'s Court',
             'Opposing an application or applying to set an order aside',
             'Enforcing orders where they are breached',
             'Protection from Harassment Act applications where the parties are not in a domestic relationship',
             'Urgent applications to keep you and your children safe'])],
         'There is no court fee to apply for a protection order. If you are in danger now, call the SAPS on 10111. The GBV Command Centre is open around the clock on 0800 428 428.'),
        ('agreements', 'Relationship & Property Agreements',
         'People live together, marry under customary law or enter civil unions. Each arrangement has legal consequences for property, maintenance and inheritance.',
         [('What we handle', [
             'Life partnership and cohabitation agreements',
             'Registering and proving customary marriages',
             'Civil union agreements',
             'Applications to change the matrimonial property system',
             'Wills and estate planning that fit your family structure, through our <a href="wills-estates.html">Wills &amp; Estates</a> team'])],
         ''),
    ],
    steps=[
        ('Confidential consultation', 'We listen to your situation, explain your rights and give you an honest view of the options and the likely cost.'),
        ('Urgent protection', 'If safety, children or money are at immediate risk, we act first, with a protection order, an interim order or an urgent application.'),
        ('Settlement first', 'We negotiate directly or through mediation. A signed settlement agreement is usually quicker, cheaper and less damaging than a trial.'),
        ('Court if needed', 'If the other side will not settle, we issue and run the matter in the right court and keep you informed at each stage.'),
        ('Order and enforcement', 'We make sure the final order or agreement is made an order of court, and enforce it if it is not followed.'),
    ],
    faqs=[
        ('How long does a divorce take?', 'An uncontested divorce, where both spouses sign a settlement agreement, can be finalised in a matter of weeks to a few months once papers are issued. A contested divorce takes much longer, often a year or more, depending on the issues and the court roll.'),
        ('Do I have to prove my spouse was at fault?', 'No. The ground for divorce is that the marriage has broken down irretrievably. Conduct can still matter when a court decides on forfeiture of benefits or maintenance.'),
        ('Who will the children live with?', 'The court decides in the best interests of each child. There is no automatic preference for either parent. Parents are encouraged to agree a parenting plan, and the Family Advocate may be asked to report in a contested matter.'),
        ('Can a maintenance order be changed?', 'Yes. Either parent can apply to vary an order if their circumstances or the child\'s needs have changed materially.'),
        ('What does it cost to get a protection order?', 'There is no court fee to apply. You do not need an attorney for the first application, but we can prepare it, represent you at the return date and deal with any breach.'),
    ],
    checklist=[
        'Identity documents for you and your spouse or partner',
        'Marriage certificate, and any antenuptial contract',
        'Birth certificates of your children',
        'Three months of payslips and bank statements',
        'A list of assets and debts, with approximate values',
        'Details of current care and contact arrangements',
        'Any court orders, protection orders or letters already received',
        'A short timeline of key events',
        'Your monthly household and child expenses',
    ],
    related=['wills-estates.html', 'notarial-services.html', 'civil-law.html', 'criminal-law.html'],
    cta_head='Need Advice on a Family Matter?',
    cta_text='Speak to an attorney in confidence. We will explain your options and the costs before you decide anything.',
)

# ---------------------------------------------------------------- Labour law
PAGES['labour-law.html'] = dict(
    nav_title='CCMA & Employment Disputes',
    title='CCMA & Employment Disputes | Unfair Dismissal, Retrenchment | Linda Chirwa Attorneys',
    meta='Unfair dismissal, retrenchment, unfair labour practices and CCMA representation in South Africa, for employees and employers. Linda Chirwa Attorneys.',
    h1='CCMA & Employment Disputes',
    lead='Representation for employees and employers in dismissals, unfair labour practices and retrenchments, at the CCMA and in the Labour Court.',
    intro='Employment disputes run on strict deadlines. A dismissal that is not referred in time can be lost before the merits are ever heard. **We tell you early whether you have a case, what you can realistically recover or risk, and what the process will cost.** We act for employees who have been dismissed or treated unfairly, and for employers who need to dismiss fairly or defend a claim.',
    areas=[
        ('dismissal', 'Unfair Dismissal',
         'A dismissal is fair only if there is a fair reason and a fair procedure. The Labour Relations Act 66 of 1995 protects employees from dismissal for misconduct, incapacity, poor performance or operational reasons where the employer has not met that standard.',
         [('What we handle', [
             'Misconduct dismissals and the fairness of the disciplinary hearing',
             'Dismissal for poor performance or incapacity, including ill health',
             'Automatically unfair dismissals, such as dismissal for pregnancy, union activity or making a protected disclosure',
             'Constructive dismissal, where an employee resigns because the employer made continued employment intolerable',
             'Dismissal of employees on fixed-term contracts and repeated renewals',
             'Defending employers against dismissal claims'])],
         'A dismissal dispute must be referred to the CCMA within 30 days of the dismissal. Late referrals need condonation, which is not guaranteed. Do not wait.'),
        ('unfair-labour-practice', 'Unfair Labour Practices',
         'An unfair labour practice is unfair conduct by an employer about promotion, demotion, training, benefits, suspension, discipline short of dismissal, or the provision of reasons for a decision.',
         [('What we handle', [
             'Unfair suspension, demotion and disciplinary action',
             'Unfair refusal to promote or to reinstate or re-employ',
             'Benefits and pay disputes that amount to an unfair labour practice',
             'Occupational detriment after making a protected disclosure',
             'Defending employers against these claims'])],
         'An unfair labour practice must usually be referred within 90 days of the act or omission.'),
        ('ccma', 'CCMA Conciliation & Arbitration',
         'The Commission for Conciliation, Mediation and Arbitration hears most employment disputes first. There is no fee to refer a dispute.',
         [('How the process works', [
             'The dispute is referred, and a conciliation is set down, usually within about 30 days',
             'A commissioner tries to settle the matter at conciliation',
             'If it does not settle, the matter goes to arbitration, where evidence is led and the commissioner issues a binding award',
             'In some cases the matter goes to the Labour Court instead']),
          ('How we help', [
             'Referring the dispute correctly and in time, including condonation applications',
             'Preparing your case, witnesses and documents',
             'Representing you at arbitration where the rules allow legal representation',
             'Reviewing or enforcing awards'])],
         'Legal representation is not allowed at conciliation, and at arbitration of misconduct and incapacity dismissals it needs the commissioner\'s permission. We prepare you thoroughly for those hearings.'),
        ('retrenchment', 'Retrenchment & Operational Requirements',
         'Retrenchment must follow a consultation process before anyone is dismissed. Section 189 of the Labour Relations Act sets out what employers must do, and larger exercises have extra requirements.',
         [('For employers', [
             'Planning a lawful and defensible retrenchment',
             'Section 189 notices, consultation and selection criteria',
             'Calculating and recording severance pay',
             'Defending retrenchment disputes']),
          ('For employees', [
             'Checking whether the process and selection were fair',
             'Severance pay, which is at least one week\'s remuneration for each completed year of service',
             'Challenging a retrenchment that is really a disguised dismissal'])],
         ''),
        ('discrimination', 'Discrimination, Harassment & Occupational Detriment',
         'The Employment Equity Act 55 of 1998 prohibits unfair discrimination in employment, and workplace harassment can ground a claim against the employer.',
         [('What we handle', [
             'Claims of discrimination on listed grounds such as race, gender, disability, age and pregnancy',
             'Sexual harassment complaints and the employer\'s duty to act',
             'Equal pay disputes',
             'Protected disclosure and whistleblower protection claims'])],
         ''),
        ('wages', 'Wages, Leave & Contract Claims',
         'The Basic Conditions of Employment Act 75 of 1997 sets minimum standards on working time, leave, notice and pay.',
         [('What we handle', [
             'Unpaid wages, overtime, leave pay and notice pay',
             'Breach of an employment contract',
             'Disputes over bonuses, commission and deductions',
             'Recovery through the CCMA, the Labour Court or the civil courts'])],
         ''),
    ],
    steps=[
        ('Quick assessment', 'We check the dates first, because deadlines decide what is still possible, then the merits and the likely outcome.'),
        ('Refer the dispute', 'We refer the matter to the CCMA or the bargaining council, with condonation if the referral is late.'),
        ('Conciliation', 'We negotiate for a settlement. Many disputes end here.'),
        ('Arbitration or Labour Court', 'If there is no settlement, we prepare your evidence and argue the matter.'),
        ('Award and enforcement', 'We enforce the award, or review it where the commissioner got it wrong.'),
    ],
    faqs=[
        ('How long do I have to challenge a dismissal?', 'Thirty days from the date of dismissal to refer an unfair dismissal dispute to the CCMA or the relevant bargaining council. Late referrals need condonation. Speak to us as soon as you are dismissed.'),
        ('What can I get if the dismissal was unfair?', 'The commissioner can order reinstatement or re-employment, or compensation. Compensation for an unfair dismissal is capped at 12 months\' remuneration, and at 24 months for an automatically unfair dismissal.'),
        ('Do I need a lawyer at the CCMA?', 'You do not have to have one, and the rules limit legal representation at conciliation and at some arbitrations. Preparation by an attorney still makes a real difference to how your case is presented.'),
        ('Can I be dismissed during probation?', 'Probation does not remove your protection. A dismissal must still be for a fair reason and follow a fair process, although the standard applied to a probationer can differ.'),
        ('What is constructive dismissal?', 'It is where an employee resigns because the employer has made continued employment intolerable, and the employee can show that the employer\'s conduct, not their own choice, ended the employment.'),
        ('Does my employer have to hold a hearing before dismissing me?', 'A dismissal for misconduct must follow a fair procedure, which usually means notice of the allegations and an opportunity to respond. The form can vary with the size of the business and the seriousness of the matter.'),
    ],
    checklist=[
        'Your contract of employment and any policies you were given',
        'The dismissal letter, notice of hearing and the outcome',
        'The date you were dismissed or the act you are complaining about',
        'Payslips for the last three months',
        'Emails, messages or minutes that support your version',
        'Names of witnesses',
        'Any warnings or performance reviews',
        'Details of your length of service and your last salary',
        'Any CCMA or bargaining council documents already received',
    ],
    related=['employment-hr.html', 'civil-law.html', 'immigration.html', 'criminal-law.html'],
    cta_head='Dismissed or Facing a Dispute at Work?',
    cta_text='Deadlines in employment matters are short. Contact us now so we can check your dates and your options.',
)

# ---------------------------------------------------------------- Immigration
PAGES['immigration.html'] = dict(
    nav_title='Immigration & Permits',
    title='Immigration & Permits | Visas, Permanent Residence, Citizenship | Linda Chirwa Attorneys',
    meta='Visas, permanent residence, citizenship and appeals for South Africa. Careful applications, clear timelines and honest advice. Linda Chirwa Attorneys.',
    h1='Immigration & Permits',
    lead='Visas, permanent residence, citizenship and appeals, prepared carefully so your application is complete the first time.',
    intro='Immigration applications are decided on paper, and a missing document or an incorrect form can mean a refusal and months lost. **We assess whether you qualify before you apply, prepare a complete application, and guide you through the process and any appeal.** We act for individuals, families and employers across South Africa. Processing times are set by the Department of Home Affairs and we cannot control them, but we can make sure your file is in order.',
    areas=[
        ('visas', 'Temporary Residence Visas',
         'The Immigration Act 13 of 2002 provides for several categories of temporary residence. Which one fits depends on why you are coming and for how long.',
         [('Common categories', [
             'Visitor\'s visas for tourism, short business trips and similar purposes',
             'Study visas for learners and students',
             'Work visas, including critical skills, general work and intra-company transfer visas',
             'Business visas for people starting or investing in a business',
             'Retired person\'s visas',
             'Medical treatment visas and exchange visas'])],
         'We tell you which category fits, what evidence it needs and whether your plan is realistic before you spend money on an application.'),
        ('work', 'Work Visas & Employer Support',
         'Employers who hire foreign nationals have their own obligations, and the visa must match the job.',
         [('What we handle', [
             'Work visa applications for individuals and for employers',
             'Documents such as the employer letter, qualifications evaluation and police clearance',
             'Intra-company transfers',
             'Renewals, amendments and changes of employer or conditions',
             'Advising employers on compliance when employing foreign nationals'])],
         ''),
        ('family', 'Spouse, Life Partner & Family Visas',
         'South Africans and permanent residents can sponsor a spouse, a life partner or other close relatives, subject to proof that the relationship is genuine.',
         [('What we handle', [
             'Spousal and life partner visas',
             'Relatives\' visas',
             'Proof of a life partnership, including a notarial partnership agreement from our <a href="notarial-services.html">Notarial Services</a>',
             'Visas for dependent children'])],
         ''),
        ('permanent', 'Permanent Residence',
         'Permanent residence is granted in specific categories, such as after several years on a qualifying work visa, through a relationship with a South African or permanent resident, or through a business or retirement route.',
         [('What we handle', [
             'Assessing which category you qualify for',
             'Preparing and submitting the application and supporting evidence',
             'Responding to queries and requests from the Department',
             'Renewing and replacing permanent residence permits'])],
         'These applications take a long time. A complete, well-organised file is the best protection against delay.'),
        ('citizenship', 'Citizenship',
         'Citizenship may be acquired by birth, by descent or by naturalisation under the South African Citizenship Act 88 of 1995.',
         [('What we handle', [
             'Naturalisation applications by permanent residents who meet the residence requirements',
             'Citizenship by descent and proof of a parent\'s citizenship',
             'Registration of births abroad',
             'Loss of, retention of and resumption of citizenship'])],
         ''),
        ('appeals', 'Appeals, Reviews & Refusals',
         'A refusal is not always the end. There are internal appeal routes, and a decision that was unlawful or unreasonable can be taken on review.',
         [('What we handle', [
             'Appeals to the Director-General against refusals, which have short deadlines',
             'Further appeals to the Minister',
             'Review applications in the High Court',
             'Late and incomplete application issues'])],
         'The deadline to appeal a refusal is short, often 10 working days from notice. If you have been refused, contact us immediately.'),
        ('undesirable', 'Overstaying & Declarations of Undesirability',
         'Overstaying a visa, or breaching its conditions, can lead to a ban on returning to South Africa, sometimes for years.',
         [('What we handle', [
             'Advice on the consequences of an overstay',
             'Representations and appeals against a declaration of undesirability',
             'Applications for waivers and for the lifting of bans where the law allows',
             'Asylum and refugee matters under the Refugees Act 130 of 1998'])],
         ''),
    ],
    steps=[
        ('Eligibility assessment', 'We review your situation and tell you which visa or permit fits, and whether you qualify.'),
        ('Document checklist', 'We give you a precise list of documents and help you obtain them, including certified and apostilled copies.'),
        ('Preparing the application', 'We complete the forms, assemble the file and check it against the Department\'s requirements.'),
        ('Submission and follow-up', 'We lodge the application, usually through a VFS Global centre, track it and respond to queries.'),
        ('Outcome, renewal or appeal', 'We collect the outcome and diarise renewals. If the application is refused, we assess an appeal at once.'),
    ],
    faqs=[
        ('How long does a visa application take?', 'It varies widely between categories and over time, and the Department of Home Affairs controls it. We tell you what the current experience is, but we cannot guarantee a processing time.'),
        ('Can I work while my application is pending?', 'Not automatically. Whether you may work depends on your current visa and its conditions. Do not assume you can. Ask us before you start.'),
        ('What if my application is refused?', 'There is a right of appeal, and the deadline is short, often 10 working days from notice of the refusal. Contact us immediately so the appeal is filed in time.'),
        ('What happens if I overstay?', 'You can be declared undesirable and banned from returning, sometimes for several years. If you have overstayed, get advice before you leave the country or apply for anything.'),
        ('Do I need documents apostilled or translated?', 'Often yes. Foreign documents usually need an apostille or legalisation, and documents not in English may need a sworn translation. Our notaries can arrange this through our <a href="notarial-services.html#apostille">apostille service</a>.'),
    ],
    checklist=[
        'Valid passport with enough blank pages and validity',
        'Your current visa or permit, if you have one',
        'Proof of the purpose of your stay, such as a job offer or admission letter',
        'Police clearance certificates from the countries you have lived in',
        'Medical and radiological reports where required',
        'Proof of relationship, such as marriage certificate or partnership agreement',
        'Proof of funds or financial means',
        'Qualifications and, where needed, an evaluation from SAQA',
        'Passport photographs and proof of address',
    ],
    related=['notarial-services.html', 'labour-law.html', 'family-law.html', 'employment-hr.html'],
    cta_head='Planning a Move to South Africa?',
    cta_text='Tell us your plans and your timeline. We will explain which route fits and what it will take.',
)

# ---------------------------------------------------------------- Company formation
PAGES['company-formation.html'] = dict(
    nav_title='Company Formation & Governance',
    title='Company Formation & Governance | CIPC Registration, Shareholders | Linda Chirwa Attorneys',
    meta='Company registration with CIPC, shareholders\' agreements, directors\' duties and annual compliance for South African businesses. Linda Chirwa Attorneys.',
    h1='Company Formation & Governance',
    lead='Register the right structure, set the rules between shareholders in writing, and keep the company compliant.',
    intro='The structure you choose on day one affects your tax, your personal liability and how easily you can bring in partners or investors later. **We help you choose the right structure, register it properly, and put the agreements in place that protect you when the business grows or the owners disagree.** We act for founders, family businesses and established companies.',
    areas=[
        ('structure', 'Choosing a Structure',
         'South African businesses usually operate as a private company, a non-profit company, a partnership, a trust or as a sole proprietor. Each has different consequences for liability, tax and administration.',
         [('Options we advise on', [
             'Private company (Pty) Ltd, the most common structure for trading businesses',
             'Public companies, personal liability companies and non-profit companies',
             'Partnerships and sole proprietorships, and when to move from one to a company',
             'Trusts for holding assets and family businesses, in coordination with our estate planning team',
             'Existing close corporations, which can still operate but cannot be newly registered'])],
         'We explain the trade-offs in plain terms and recommend a structure for your goals, not a default.'),
        ('registration', 'Registering with CIPC',
         'Companies are registered with the Companies and Intellectual Property Commission under the Companies Act 71 of 2008.',
         [('What we handle', [
             'Name reservation and checking for conflicts',
             'Drafting a tailored Memorandum of Incorporation',
             'Registering the company, directors and shareholders',
             'Registering for tax, VAT, PAYE, UIF and the Compensation Fund where applicable',
             'Share certificates, registers and the initial resolutions',
             'Beneficial ownership information filed with CIPC'])],
         'Registration itself is often quick, but the work that matters is in the Memorandum of Incorporation and the agreements around it.'),
        ('shareholders', 'Shareholders\' Agreements',
         'The Memorandum of Incorporation is a public document. A shareholders\' agreement is private, and it is where owners record what they have really agreed.',
         [('What we cover', [
             'Who contributes what, and who is entitled to what',
             'Decision-making, deadlock and reserved matters',
             'Share transfers, pre-emption rights and drag-along and tag-along rights',
             'Leaving the business: death, disability, divorce and exit',
             'Restraints of trade and protection of confidential information',
             'Valuation and buy-out mechanisms'])],
         'Most shareholder disputes are expensive because nothing was agreed at the start. A good agreement is cheapest when you do not need it.'),
        ('governance', 'Directors & Governance',
         'Directors owe duties to the company and can be personally liable for breaches, including reckless trading.',
         [('What we advise on', [
             'Directors\' duties, conflicts of interest and personal liability',
             'Board and shareholder meetings, resolutions and minutes',
             'Appointing and removing directors',
             'Company secretary requirements',
             'Financial assistance, loans to directors and related-party transactions',
             'Governance policies suited to the size of the business'])],
         ''),
        ('compliance', 'Annual Compliance',
         'Companies have continuing duties, and failure to keep up can lead to deregistration and penalties.',
         [('What we handle', [
             'Annual returns to CIPC, due after each anniversary of incorporation',
             'Updating directors, addresses and beneficial ownership information',
             'Annual financial statements and audit or independent review requirements',
             'Reinstating companies that have been deregistered',
             'Compliance checks before a sale, financing or investment'])],
         ''),
        ('changes', 'Changes, Restructuring & Winding Up',
         'Companies change over time. Shareholders come and go, businesses are restructured, and some are closed.',
         [('What we handle', [
             'Share transfers and new share issues',
             'Changing a company name or amending the Memorandum of Incorporation',
             'Group restructures and holding company structures',
             'Voluntary deregistration and winding up',
             'Business rescue and liquidation, handled with our <a href="civil-law.html#insolvency">insolvency team</a>'])],
         ''),
    ],
    steps=[
        ('Understand the plan', 'We ask who the owners are, who funds the business, what could go wrong and where you want to be in five years.'),
        ('Choose the structure', 'We recommend a structure and explain the tax and liability consequences, so you can decide with the full picture.'),
        ('Register and document', 'We register the company and draft the Memorandum of Incorporation, resolutions and the shareholders\' agreement.'),
        ('Set up compliance', 'We register for tax and labour obligations and give you a calendar of what is due and when.'),
        ('Ongoing support', 'We update your records as the business changes and are on hand when you need advice on a decision.'),
    ],
    faqs=[
        ('Should I register a company or trade as a sole proprietor?', 'A company is a separate legal person, which can limit your personal exposure for business debts, and it is easier to bring in partners. It also carries compliance duties and costs. The right choice depends on the risks of your business, your tax position and your plans.'),
        ('How long does it take to register a company?', 'The registration itself is often completed within days, though timing depends on CIPC. Allow more time if you need a tailored Memorandum of Incorporation and a shareholders\' agreement.'),
        ('Do I need a shareholders\' agreement?', 'If there is more than one shareholder, yes. Without one, the default rules apply, and they rarely fit what the owners expected, especially when a dispute arises or one shareholder wants out.'),
        ('Can I be personally liable as a director?', 'Yes, in certain circumstances, for example for reckless or fraudulent trading, for breach of duty, or where you have signed a personal suretyship. We explain where your exposure lies.'),
        ('Can I still register a close corporation?', 'No. New close corporations can no longer be registered, although existing ones continue and can be converted to companies.'),
    ],
    checklist=[
        'Identity documents and proof of address for every director and shareholder',
        'Your proposed company names, in order of preference',
        'The shareholding you want for each person',
        'The nature of the business and its intended activities',
        'Existing tax numbers, if you already trade',
        'Details of any loans or assets going into the company',
        'Any existing agreements between the owners',
        'Whether you expect to employ staff or register for VAT',
    ],
    related=['commercial-contracts.html', 'mergers-acquisitions.html', 'employment-hr.html', 'civil-law.html'],
    cta_head='Starting or Restructuring a Business?',
    cta_text='Tell us what you are building. We will recommend a structure and a plan before you register anything.',
)

# ---------------------------------------------------------------- Commercial contracts
PAGES['commercial-contracts.html'] = dict(
    nav_title='Contracts & Transactions',
    title='Commercial Contracts & Transactions | Drafting and Review | Linda Chirwa Attorneys',
    meta='Drafting, reviewing and negotiating commercial contracts in South Africa, from supply and service agreements to leases and suretyships. Linda Chirwa Attorneys.',
    h1='Contracts & Transactions',
    lead='Contracts drafted and reviewed so the deal on paper matches the deal you made, and holds up if it is tested.',
    intro='Most commercial disputes turn on a clause someone did not read, or an obligation that was never written down. **A good contract costs far less than a bad dispute.** We draft, review and negotiate commercial agreements for businesses of all sizes, and we write them in plain language so you can run your business from them. Where a contract does break down, our <a href="civil-law.html">litigation team</a> picks up the file.',
    areas=[
        ('drafting', 'Contract Drafting',
         'We draft agreements from your instructions, not from a generic template, and we make sure the terms suit how your business really works.',
         [('Agreements we draft', [
             'Sale, supply and distribution agreements',
             'Service, consulting and subcontracting agreements',
             'Agency and reseller agreements',
             'Loan agreements and acknowledgements of debt',
             'Confidentiality and non-disclosure agreements',
             'Standard terms and conditions for customers and suppliers'])],
         ''),
        ('review', 'Review & Negotiation',
         'Before you sign, we read the agreement the way the other side\'s lawyer will read it in a dispute.',
         [('What we check', [
             'Payment, delivery and acceptance terms',
             'Termination, cancellation and breach clauses',
             'Limits on liability and indemnities',
             'Jurisdiction, notices and the address chosen for legal service',
             'Whole-agreement and non-variation clauses, which can stop later informal changes from counting',
             'Obligations that are unclear, one-sided or impossible to perform'])],
         'We tell you plainly which points are worth fighting for and which are not.'),
        ('leases', 'Commercial Leases',
         'Lease terms decide your costs and your flexibility for years.',
         [('What we handle', [
             'Drafting and negotiating commercial lease agreements for landlords and tenants',
             'Escalation, renewal, deposit and repair clauses',
             'Long leases that must be registered by notarial deed, through our <a href="notarial-services.html#notarial-leases">Notarial Services</a>',
             'Cancellation, arrears and eviction, through our <a href="civil-law.html#evictions">civil litigation team</a>'])],
         ''),
        ('suretyships', 'Suretyships & Security',
         'A suretyship makes someone personally liable for another\'s debt. The law requires it to be in writing and signed by the surety, and the wording matters.',
         [('What we handle', [
             'Drafting and reviewing suretyships, guarantees and cession of debts',
             'Advising directors before they sign personal suretyships',
             'Notarial bonds over movable assets, with our notaries',
             'Enforcing and defending claims on suretyships'])],
         ''),
        ('consumer', 'Consumer, Credit & Online Terms',
         'Contracts with consumers must comply with the Consumer Protection Act 68 of 2008 and, for credit, the National Credit Act 34 of 2005.',
         [('What we handle', [
             'Consumer-facing terms and conditions',
             'Compliance with rules on unfair terms, fixed-term contracts and cancellation',
             'Credit agreements and credit provider compliance',
             'Website terms, online sales terms and electronic contracting',
             'POPIA clauses and data processing agreements'])],
         ''),
        ('franchise', 'Franchise & Licensing',
         'Franchise agreements and licences are regulated, and they combine contract law with intellectual property.',
         [('What we handle', [
             'Franchise agreements for franchisors and franchisees',
             'Disclosure documents and compliance with the franchise rules',
             'Licence and distribution agreements',
             'Protecting the brand through our <a href="intellectual-property.html">IP team</a>'])],
         ''),
    ],
    steps=[
        ('Understand the deal', 'We ask what you have agreed, what matters most to you and what could go wrong.'),
        ('Draft or review', 'We prepare the agreement, or mark up the one you have been sent, with a short summary of the real risks.'),
        ('Negotiate', 'We deal with the other side, or advise you while you do, and we keep the document consistent as terms change.'),
        ('Sign properly', 'We make sure the right people sign in the right capacity, with the right formalities.'),
        ('Keep a record', 'You receive the signed agreement and a note of key dates, such as renewals, review dates and notice periods.'),
    ],
    faqs=[
        ('Is a verbal agreement binding?', 'Often yes, but it is hard to prove, and some contracts must be in writing to be valid, such as the sale of land and suretyships. A written agreement avoids arguments about what was said.'),
        ('Can I use a template from the internet?', 'You can, but templates rarely fit your business and may not comply with South African law. A short review by an attorney usually costs far less than the dispute a bad template can cause.'),
        ('What if the other party breaches the contract?', 'It depends on the clauses and the breach. You may be able to demand performance, cancel and claim damages. Do not cancel before getting advice, because wrongful cancellation can itself be a breach. Our <a href="civil-law.html#contract">litigation team</a> can help.'),
        ('Does a contract have to be signed by a lawyer or notary?', 'No. Most contracts need only the parties\' signatures. A few, such as long leases and antenuptial contracts, need a notary.'),
        ('How long does a contract review take?', 'A simple agreement can be reviewed in a few days. Larger or negotiated agreements take longer. We agree a timeline with you at the start.'),
    ],
    checklist=[
        'The draft agreement, or the key terms you have agreed',
        'Full names and registration details of every party',
        'Any emails or quotations that record what was agreed',
        'The commercial terms: price, payment dates, delivery, duration',
        'Any previous agreements with the same party',
        'Your concerns, and the clauses you are unsure about',
        'The date by which the contract must be signed',
        'Who will sign for each party, and in what capacity',
    ],
    related=['company-formation.html', 'mergers-acquisitions.html', 'civil-law.html', 'intellectual-property.html'],
    cta_head='Have a Contract to Draft or Review?',
    cta_text='Send us the document or the key terms. We will tell you what it needs and what it will cost.',
)

# ---------------------------------------------------------------- M&A
PAGES['mergers-acquisitions.html'] = dict(
    nav_title='Mergers & Acquisitions',
    title='Mergers & Acquisitions | Business Sales, Due Diligence | Linda Chirwa Attorneys',
    meta='Buying or selling a business in South Africa: sale of business and share sale agreements, due diligence, approvals and closing. Linda Chirwa Attorneys.',
    h1='Mergers & Acquisitions',
    lead='Buying or selling a business, structured and documented so the price you agree is the price you get.',
    intro='Selling or buying a business is usually the biggest transaction an owner will ever do. **We run the legal side from the first term sheet to closing: structure, due diligence, the agreement, approvals and the handover.** We act for sellers and buyers of owner-managed and mid-sized businesses, and we work closely with your accountants and financial advisers.',
    areas=[
        ('business-sale', 'Sale of a Business',
         'In a sale of business, the buyer acquires the assets and, usually, the liabilities it agrees to take, as a going concern.',
         [('What we handle', [
             'Letters of intent, term sheets and confidentiality agreements',
             'Sale of business agreements, including warranties and indemnities',
             'Transferring contracts, licences, premises and stock',
             'Employee transfers and VAT and tax treatment of a going concern',
             'Restraints of trade for sellers and key people'])],
         ''),
        ('share-sale', 'Share Sales & Investments',
         'In a share sale, the buyer takes over the company itself, with its history and liabilities.',
         [('What we handle', [
             'Share purchase agreements',
             'Bringing in investors and drafting subscription agreements',
             'Management buy-outs and buy-ins',
             'Conditions precedent and timelines to closing',
             'Securities transfer and share register updates'])],
         ''),
        ('due-diligence', 'Due Diligence',
         'Due diligence is the legal and commercial check a buyer runs before committing, and the one a seller should run first.',
         [('What we review', [
             'Corporate records, shareholdings and authority to sell',
             'Material contracts and change-of-control clauses',
             'Property, leases and licences',
             'Employment and labour liabilities',
             'Litigation, regulatory compliance and intellectual property',
             'Tax and debt that could transfer with the business'])],
         'Findings feed the price, the warranties and the conditions of the deal, so we report plainly on what matters.'),
        ('approvals', 'Approvals & Consents',
         'Some transactions cannot close until third parties approve them.',
         [('What we advise on', [
             'Shareholder resolutions, including special resolutions required when a company disposes of all or most of its assets',
             'Competition law notification and approval, where the size of the parties makes the transaction notifiable',
             'Landlord, funder and counterparty consents',
             'Sector regulator approvals where relevant'])],
         ''),
        ('employees-tax', 'Employees, Tax & Property',
         'These issues are often overlooked until late in the deal.',
         [('What we advise on', [
             'The transfer of employees on the same terms when a business is sold as a going concern',
             'VAT, capital gains tax, transfer duty and securities transfer tax',
             'Transferring immovable property, with our <a href="conveyancing.html">conveyancing team</a>',
             'Structuring the price, including deferred and earn-out payments'])],
         ''),
        ('closing', 'Closing & After',
         'Closing is a process, not a signature.',
         [('What we handle', [
             'Closing checklists and signing arrangements',
             'Payment mechanics, escrow and retention of part of the price',
             'Handover documents and register updates',
             'Post-closing disputes over warranties and price adjustments'])],
         ''),
    ],
    steps=[
        ('Terms and confidentiality', 'We settle a confidentiality agreement and record the main commercial terms.'),
        ('Due diligence', 'We review the target business, or prepare yours for review, and report on the issues.'),
        ('Negotiate the agreement', 'We draft and negotiate the agreement, with warranties, conditions and protections that match the risks found.'),
        ('Satisfy the conditions', 'We manage approvals, consents and the other steps that must happen before closing.'),
        ('Close and hand over', 'We close the deal, move the money and assets, and attend to post-closing matters.'),
    ],
    faqs=[
        ('Should I sell the business or the shares?', 'It depends on tax, risk and the buyer\'s goals. Buyers often prefer an asset sale because they can leave liabilities behind. Sellers often prefer a share sale for tax reasons. We model both with your accountant.'),
        ('What is due diligence?', 'It is the structured review a buyer carries out to check what it is buying. Results can change the price, the warranties or whether the deal proceeds.'),
        ('What happens to the employees?', 'When a business is transferred as a going concern, section 197 of the Labour Relations Act transfers the employees to the buyer automatically, on the same terms, and the seller and buyer share certain liabilities.'),
        ('Does the deal need Competition Commission approval?', 'Only if the parties meet the size thresholds for a notifiable merger. We check this at the start, because a notifiable deal cannot close without approval.'),
        ('What are warranties and indemnities?', 'Warranties are statements the seller makes about the business. If they are untrue, the buyer can claim. Indemnities protect the buyer against specific known risks.'),
    ],
    checklist=[
        'The company\'s registration documents, share register and Memorandum of Incorporation',
        'Latest annual financial statements and management accounts',
        'List of material contracts, leases and licences',
        'Employee list with roles, salaries and contracts',
        'Details of any loans, security and guarantees',
        'Details of property owned or leased',
        'Pending or threatened claims',
        'Tax clearance and compliance records',
        'Your proposed price and timetable',
    ],
    related=['company-formation.html', 'commercial-contracts.html', 'conveyancing.html', 'employment-hr.html'],
    cta_head='Buying or Selling a Business?',
    cta_text='Speak to us early, before terms are signed. Early structure advice often protects more value than late negotiation.',
)

# ---------------------------------------------------------------- IP
PAGES['intellectual-property.html'] = dict(
    nav_title='Intellectual Property',
    title='Intellectual Property | Trade Marks, Copyright, Patents | Linda Chirwa Attorneys',
    meta='Trade mark registration, copyright, patents, designs, licensing and enforcement in South Africa. Protect your brand and ideas. Linda Chirwa Attorneys.',
    h1='Intellectual Property',
    lead='Protect your brand, your creative work and your inventions, and act when someone copies them.',
    intro='Your name, your logo and your know-how often outlast any single product, and they are the first things competitors copy. **We help you secure the rights you can register, record the ones that arise automatically, and enforce them when they are infringed.** We act for start-ups, creators and established brands.',
    areas=[
        ('trade-marks', 'Trade Marks',
         'A trade mark identifies the origin of your goods or services. Registration under the Trade Marks Act 194 of 1993 gives you the exclusive right to use the mark for the goods and services it covers.',
         [('What we handle', [
             'Searches to check whether a name or logo is available',
             'Filing applications with CIPC in the right classes',
             'Responding to examination reports and oppositions',
             'Renewals, which fall due every ten years',
             'Opposing or cancelling conflicting marks',
             'Recording assignments and licences'])],
         'Register before you spend on branding. A search first can save you from rebranding later.'),
        ('copyright', 'Copyright',
         'Copyright protects original literary, artistic and musical works, films, software and more. It arises automatically when the work is created, and no registration is needed.',
         [('What we handle', [
             'Advising on who owns a work, including works made by employees and contractors',
             'Assignments and licences of copyright',
             'Copyright notices and website content',
             'Software and database ownership',
             'Takedown notices and infringement claims'])],
         'For most literary and artistic works, copyright lasts for the author\'s life and 50 years after death. Without a written assignment, a commissioned creator often keeps the copyright.'),
        ('patents', 'Patents & Designs',
         'A patent protects a new invention that involves an inventive step and can be applied in industry. A registered design protects the look of an article, or its function in some cases.',
         [('What we handle', [
             'Advising on whether an invention is patentable and when to disclose it',
             'Working with patent attorneys on drafting and filing',
             'Design registrations under the Designs Act 195 of 1993',
             'Licensing and commercialising inventions',
             'Disputes over ownership and infringement'])],
         'Patents last up to 20 years from filing, subject to annual renewal fees. Public disclosure before filing can destroy your right, so speak to us before you publish or pitch.'),
        ('enforcement', 'Enforcement & Disputes',
         'When someone copies your brand or work, speed and the right remedy matter.',
         [('What we handle', [
             'Letters of demand and cease and desist notices',
             'Urgent interdicts to stop infringement and passing off',
             'Damages and the surrender of profits',
             'Counterfeit goods complaints under the Counterfeit Goods Act 37 of 1997',
             'Defending allegations of infringement against you'])],
         ''),
        ('licensing', 'Licensing, Assignments & Ownership',
         'Intellectual property creates value only when ownership and rights of use are clear.',
         [('What we handle', [
             'Licence and franchise agreements',
             'Assignments of trade marks, copyright and designs',
             'IP clauses in employment and contractor agreements',
             'IP due diligence when buying or selling a business, with our <a href="mergers-acquisitions.html">M&amp;A team</a>',
             'Confidentiality and trade secret protection'])],
         ''),
        ('domains', 'Domain Names & Online Brand',
         'Your online presence can be hijacked as easily as it is built.',
         [('What we handle', [
             'Disputes over .co.za and other domain names',
             'Social media account and handle disputes',
             'Online impersonation and brand misuse',
             'Terms for websites, marketplaces and influencers'])],
         ''),
    ],
    steps=[
        ('Identify what you have', 'We list your brands, works and inventions, and who owns each of them.'),
        ('Search and advise', 'We search the registers, advise on the strongest form of protection and explain the cost.'),
        ('File and register', 'We prepare and file applications, respond to examiners and track each one to registration.'),
        ('Put ownership in writing', 'We update employment, contractor and licence agreements so ownership is clear.'),
        ('Monitor and enforce', 'We diarise renewals and act quickly when we see an infringement.'),
    ],
    faqs=[
        ('Do I need to register copyright?', 'No. Copyright arises automatically when an original work is created and recorded. Keep dated drafts and files, because they are your evidence of authorship.'),
        ('How long does trade mark registration take?', 'Often a year or more, depending on examination and whether anyone opposes. Your application date still protects your priority while it is pending.'),
        ('Can I use the ® symbol?', 'Only once the mark is registered. You can use ™ for an unregistered mark that you are using or have applied to register.'),
        ('Who owns work created by an employee?', 'For works made in the course of employment, the employer is generally the first owner of copyright, subject to any agreement to the contrary. Contractors are different, so we put it in writing.'),
        ('What can I do if someone is copying my brand?', 'Collect evidence, and then contact us. Depending on your rights, we can send a demand, apply for an urgent interdict and claim damages.'),
    ],
    checklist=[
        'The names, logos and slogans you use or plan to use',
        'The goods and services each one covers',
        'Dates of first use, with examples',
        'Details of who created your logo, website and content',
        'Any existing registrations, applications or licences',
        'Descriptions of inventions or unique processes, kept confidential',
        'Examples of any suspected copying, with dates and screenshots',
        'Your employment and contractor agreements',
    ],
    related=['commercial-contracts.html', 'company-formation.html', 'mergers-acquisitions.html', 'civil-law.html'],
    cta_head='Protect What You Have Built',
    cta_text='Tell us what you want to protect or what is being copied. We will explain the options and the cost.',
)

# ---------------------------------------------------------------- Employment & HR
PAGES['employment-hr.html'] = dict(
    nav_title='Employment & HR Compliance',
    title='Employment & HR Compliance | Contracts, Discipline, Policies | Linda Chirwa Attorneys',
    meta='Employment contracts, HR policies, disciplinary processes, retrenchments and compliance advice for South African employers. Linda Chirwa Attorneys.',
    h1='Employment & HR Compliance',
    lead='Practical employment advice for employers: contracts, policies, discipline and compliance that stand up at the CCMA.',
    intro='Most employment disputes are won or lost on the paperwork and the process, long before a case is referred. **We help employers put the right contracts and policies in place, follow a fair process when things go wrong, and defend the decision if it is challenged.** If you are an employee with a dispute, see our <a href="labour-law.html">CCMA &amp; Employment Disputes</a> page.',
    areas=[
        ('contracts', 'Contracts & Policies',
         'Written contracts and clear policies set expectations and make later decisions defensible.',
         [('What we handle', [
             'Employment contracts for permanent, fixed-term and part-time staff',
             'Disciplinary, grievance, leave, remote work and conduct policies',
             'Executive and senior management agreements',
             'Probation, remuneration, incentive and bonus terms',
             'Compliance with the Basic Conditions of Employment Act'])],
         ''),
        ('discipline', 'Discipline & Misconduct',
         'A fair dismissal needs a fair reason and a fair process. The form can be simple, but the steps must be there.',
         [('What we handle', [
             'Advising on whether the conduct justifies discipline or dismissal',
             'Drafting charges, notices and hearing records',
             'Chairing or advising the chairperson of disciplinary hearings',
             'Final warnings, suspensions and settlement agreements',
             'Workplace investigations into misconduct, harassment and fraud'])],
         'We check the process before you act, because a procedural mistake can turn a justified dismissal into an unfair one.'),
        ('incapacity', 'Poor Performance & Incapacity',
         'Dismissing for poor performance or ill health follows a different process from misconduct, with a duty to guide, support and consider alternatives.',
         [('What we handle', [
             'Performance management and improvement plans',
             'Incapacity processes for ill health and injury',
             'Medical evidence and accommodation',
             'Fair termination when the process has been followed'])],
         ''),
        ('retrenchment', 'Restructuring & Retrenchment',
         'Operational changes need a consultation process before any dismissal.',
         [('What we handle', [
             'Section 189 and 189A consultation processes',
             'Selection criteria, severance and notice',
             'Alternatives to retrenchment, such as short-time and voluntary packages',
             'Defending disputes about the process'])],
         ''),
        ('compliance', 'Statutory Compliance',
         'Employers must meet several overlapping statutory duties.',
         [('What we advise on', [
             'Employment equity duties and reporting, where they apply',
             'Occupational health and safety and workplace injury compensation',
             'Unemployment Insurance and skills levy obligations',
             'Data protection and employee information under POPIA',
             'Audit and risk reviews of your HR practices'])],
         ''),
        ('restraints', 'Restraints & Confidentiality',
         'A restraint of trade protects your business, but it is enforced only if it is reasonable and protects a legitimate interest.',
         [('What we handle', [
             'Drafting reasonable restraints and confidentiality undertakings',
             'Enforcing restraints and obtaining urgent interdicts',
             'Defending employees against restraints',
             'Protecting trade secrets and client relationships'])],
         ''),
        ('representation', 'Representation at the CCMA & Labour Court',
         'If a claim is referred, we represent the employer from conciliation to the Labour Court.',
         [('What we handle', [
             'CCMA conciliation and arbitration',
             'Labour Court applications and reviews',
             'Bargaining council disputes',
             'Settlement negotiations'])],
         ''),
    ],
    steps=[
        ('Review what you have', 'We look at your contracts, policies and past disputes and tell you where the risk is.'),
        ('Fix the documents', 'We update or draft the contracts and policies you need, in plain language your managers can use.'),
        ('Advise before you act', 'We advise on each step in a dispute before it is taken, which is cheaper than correcting it afterwards.'),
        ('Run the process', 'We prepare notices, run hearings and keep a clear record of the steps taken.'),
        ('Defend if challenged', 'If a claim is referred, we represent you and use the record we built.'),
    ],
    faqs=[
        ('Do I need written employment contracts?', 'The law requires employers to give employees written particulars of employment, and a proper contract is the best way to do that and to protect the business.'),
        ('Can I dismiss someone immediately for serious misconduct?', 'Even in serious cases, you must follow a fair process, which usually includes notice of the allegations and a chance to respond. Instant dismissals are the most common cause of lost cases.'),
        ('What is a fair retrenchment process?', 'A consultation process must start before dismissal, with notice, disclosure of relevant information, and genuine engagement on alternatives and selection. Severance pay is at least one week for each completed year of service.'),
        ('Are restraints of trade enforceable?', 'They can be, if they protect a legitimate interest such as client connections or confidential information, and are reasonable in scope, area and duration. A court will not enforce one that is wider than it needs to be.'),
        ('How can I reduce the risk of CCMA claims?', 'Have clear contracts and policies, apply them consistently, keep records and take advice before dismissing. Small steps taken early prevent most of the cost.'),
    ],
    checklist=[
        'Current employment contracts and any template you use',
        'Your disciplinary code and key policies',
        'The employee\'s file, including warnings and reviews',
        'Details of the incident or the performance issue',
        'Witness statements and supporting documents',
        'Details of any consultation already held',
        'Number of employees and company structure',
        'Any CCMA or bargaining council papers received',
    ],
    related=['labour-law.html', 'company-formation.html', 'immigration.html', 'commercial-contracts.html'],
    cta_head='Need HR or Employment Advice?',
    cta_text='Speak to us before you act. A short conversation can prevent a dispute and its cost.',
)

# ----------------------------------------------------------------- Hub page
HUB = dict(
    individuals=[
        ('Family Law', 'family-law.html', 'Divorce, children, maintenance and protection orders.'),
        ('Wills, Estates & Trusts', 'wills-estates.html', 'Wills, estate administration, trusts and powers of attorney.'),
        ('Property Conveyancing', 'conveyancing.html', 'Transfers, bonds, sectional title and deceased estate property.'),
        ('Notarial Services', 'notarial-services.html', 'Antenuptial contracts, notarial bonds, servitudes and apostilles.'),
        ('Criminal Defence', 'criminal-law.html', 'Bail, trials, appeals and traffic offences.'),
        ('Injury & Damages Claims', 'civil-law.html#delictual', 'Road accident, workplace injury and medical negligence claims.'),
        ('CCMA & Employment Disputes', 'labour-law.html', 'Dismissal, unfair labour practices and retrenchment.'),
        ('Immigration & Permits', 'immigration.html', 'Visas, permanent residence and citizenship.'),
    ],
    businesses=[
        ('Company Formation & Governance', 'company-formation.html', 'Registration, shareholders\' agreements and compliance.'),
        ('Contracts & Transactions', 'commercial-contracts.html', 'Drafting, review and negotiation of commercial agreements.'),
        ('Mergers & Acquisitions', 'mergers-acquisitions.html', 'Business sales, share deals and due diligence.'),
        ('Debt Collection & Litigation', 'civil-law.html#debt', 'Recovering debts and resolving commercial disputes.'),
        ('Insolvency & Business Rescue', 'civil-law.html#insolvency', 'Liquidation, sequestration and business rescue.'),
        ('Intellectual Property', 'intellectual-property.html', 'Trade marks, copyright, patents and enforcement.'),
        ('Employment & HR Compliance', 'employment-hr.html', 'Contracts, policies, discipline and compliance.'),
    ],
)

RELATED_LABELS = {
    'wills-estates.html': 'Wills & Estates',
    'notarial-services.html': 'Notarial Services',
    'civil-law.html': 'Civil Litigation',
    'criminal-law.html': 'Criminal Law',
    'conveyancing.html': 'Conveyancing',
    'family-law.html': 'Family Law',
    'labour-law.html': 'CCMA & Employment Disputes',
    'immigration.html': 'Immigration & Permits',
    'company-formation.html': 'Company Formation',
    'commercial-contracts.html': 'Contracts & Transactions',
    'mergers-acquisitions.html': 'Mergers & Acquisitions',
    'intellectual-property.html': 'Intellectual Property',
    'employment-hr.html': 'Employment & HR',
}
